name: nlp
description: Natural language processing (NLP) for Dart
version: 0.0.0
repository: https://github.com/Flutter-Bounty-Hunters/nlp

environment:
  sdk: ^3.0.0

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
