name: nlp
description: Natural language processing (NLP) for Dart
version: 0.0.0
repository: https://github.com/Flutter-Bounty-Hunters/nlp

environment:
  sdk: ^3.0.0

dependencies:
  intl: ^0.18.1
  json_annotation: ^4.8.1
  unorm_dart: ^0.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
