name: Run tests for pull requests
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the PR branch
      - uses: actions/checkout@v3

      # Setup chromedriver for integration tests
      - uses: nanasess/setup-chromedriver@2

      # Setup Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Download all the packages that the app uses
      - run: flutter pub get

      # Run all tests
      - working-directory: ./example_js_regex
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/duration/duration_parser_test.dart -d chrome
